# Generated by Django 4.0 on 2025-04-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='description',
        ),
        migrations.RemoveField(
            model_name='show',
            name='duration',
        ),
    ]
